name: Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        if: matrix.analysis
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls -n -W
          vendor/bin/php-coveralls --coverage_clover=clover.xml -v